/**
 * The shared contract. Every track imports from here.
 *
 * Merged from two branches that grew it at the same time: Track A's expanded
 * relationship axes and `Conversation`/`SocialRequest` model, and update 1's
 * topics, locations, evidence, clock and memory fields.
 *
 * `ai/types.ts` used to mirror this as a shim (that file is now deleted) and
 * adds nothing but drift.
 *
 * Where the two branches modelled the same idea, the resolution is recorded
 * next to the type. The one that matters: `Conversation` is Track A's, and the
 * mock engine's live pairwise exchange is `Thread`. See both below.
 */

export type CharacterId = string;
export type MoveId = string;
export type TopicId = string;
export type LocationId = string;
export type ConversationId = string;
export type SocialRequestId = string;
export type ThreadId = string;

// --- relationships --------------------------------------------------------

/**
 * Eight axes, from Track A. Update 1's five were a strict subset, and both
 * branches independently arrived at `anger`, so this is additive.
 *
 * The array is the source of truth — `REL_FIELDS` in `lib/format.ts` spreads
 * it, so adding an axis here reaches decay, status derivation, the effect
 * tables and the inspector bars without touching any of them.
 */
export const RELATIONSHIP_AXES = [
  "trust",
  "gratitude",
  "affection",
  "respect",
  "fear",
  "anger",
  "jealousy",
  "hate",
] as const;

export type RelationshipAxis = (typeof RELATIONSHIP_AXES)[number];

/** All axes, once a fixture or save has been through `normalizeWorld`. */
export type RelationshipValues = Record<RelationshipAxis, number>;

/**
 * Directed and pairwise: `relationships[A][B]` is A's view of B. Never write
 * both directions in one effect unless the move explicitly says so.
 *
 * Every axis is required *here*, in runtime state, because the decay pass and
 * `statusFor` do arithmetic on all of them and a `number | undefined` at every
 * read site is how that arithmetic silently becomes `NaN`. The tolerant shape
 * for data that has not been migrated yet is `RelationshipState` below;
 * `normalizeWorld` is the boundary between the two.
 *
 * `baseline` is what the end-of-tick decay pass pulls toward — without it,
 * `fear` was a ratchet with no move in the game able to lower it.
 * `lastDelta` is what moved this tick; prompts and bar animations both read it.
 * `flags` are discrete states a move sets or clears.
 * `history` is the ledger behind "who was what before".
 */
export interface Relationship extends RelationshipValues {
  baseline: RelationshipValues;
  lastDelta: Partial<RelationshipValues>;
  flags: string[];
  history: RelationshipEvent[];
}

/**
 * The loose shape at the edge: fixtures and saved games written before an axis
 * existed. Only `normalizeWorld` and Track A's scoring helpers should accept
 * it — everything downstream of normalization gets `Relationship`.
 */
export interface RelationshipState {
  trust: number;
  affection: number;
  respect: number;
  fear: number;
  gratitude?: number;
  anger?: number;
  jealousy?: number;
  hate?: number;
  baseline?: Partial<RelationshipValues>;
  lastDelta?: Partial<RelationshipValues>;
  flags?: string[];
  history?: RelationshipEvent[];
}

export type RelationshipStatus =
  | "close"
  | "friend"
  | "ally"
  | "neutral"
  | "wary"
  | "rival"
  | "estranged"
  | "hostile";

export interface RelationshipEvent {
  turn: number;
  was: RelationshipStatus;
  now: RelationshipStatus;
  because?: string;
}

// --- memory and belief ----------------------------------------------------

export type MemoryTier = "direct" | "overheard" | "told";

export interface Memory {
  id: string;
  turn: number;

  actor: CharacterId;
  target?: CharacterId;

  /** Templated by the engine — never generated by a model. */
  description: string;
  tags: string[];
  importance: number;

  /** -1..1, how good or bad this was for the owner. */
  valence: number;
  tier: MemoryTier;
  /** false = planted by SpreadRumor. The owner cannot tell. */
  accurate: boolean;

  /** A MAJOR event: exempt from the cap, floored on decay. */
  core: boolean;

  topicId?: TopicId;
  threadId?: ThreadId;
}

export interface Belief {
  id: string;
  /** Who this belief is about. A free-text description alone is untestable. */
  subject: CharacterId;
  axis?: RelationshipAxis;
  description: string;
  confidence: number;
  sourceMemoryId?: string;
}

// --- characters -----------------------------------------------------------

export interface CharacterState {
  mood: string;
  emotions: Record<string, number>;
}

export interface Character {
  id: CharacterId;
  name: string;

  traits: string[];

  state: CharacterState;

  relationships: Record<CharacterId, Relationship>;

  memories: Memory[];
  beliefs: Belief[];

  goals: string[];

  location: LocationId;
  activeThreadId?: ThreadId;
}

// --- world furniture ------------------------------------------------------

export interface Location {
  id: LocationId;
  name: string;
  connectsTo: LocationId[];
  /** Exchanges here are not overheard by anyone outside. */
  private: boolean;
}

export interface Evidence {
  id: string;
  topicId: TopicId;
  claim: string;
  heldBy: CharacterId[];
  /** false = planted. Nobody holding it can tell. */
  accurate: boolean;
  /** Who it implicates. */
  pointsAt?: CharacterId;
  /** 0..1 contribution to a suspect's confidence score. */
  weight: number;
  /** Locked evidence needs a condition met before it can be obtained. */
  locked?: boolean;
}

export interface Topic {
  id: TopicId;
  label: string;
  secret: boolean;
  awareOf: CharacterId[];
  evidence: Evidence[];
}

// --- conversations: Track A's model ---------------------------------------

export type ConversationStatus = "active" | "paused" | "ended";
export type SocialRequestStatus =
  | "pending"
  | "accepted"
  | "refused"
  | "fulfilled"
  | "failed"
  | "withdrawn";

export interface ConversationTopic {
  /** Stable category used by rules and memory retrieval. */
  kind: string;
  subject?: CharacterId;
  object?: CharacterId;
  /** Player-facing phrasing, e.g. "Whether Bob betrayed Alice". */
  summary: string;
  salience: number;
}

export interface ConversationTurn {
  turn: number;
  speaker: CharacterId;
  moveId: MoveId;
  target?: CharacterId;
  eventId?: string;
}

/**
 * Authoritative state for an interaction that is happening now. Long-term
 * recollection belongs in each character's Memory array, not in this record.
 * Part 2 will enforce that a character appears in at most one active record.
 *
 * This is Track A's model and it owns the name. The mock engine does not use
 * it yet — see `Thread`.
 */
export interface Conversation {
  id: ConversationId;
  participants: CharacterId[];
  location: LocationId;
  status: ConversationStatus;
  startedTurn: number;
  lastActiveTurn: number;
  currentSpeaker?: CharacterId;
  expectedResponder?: CharacterId;
  primaryTopic: ConversationTopic;
  secondaryTopics: ConversationTopic[];
  summary: string;
  recentTurns: ConversationTurn[];
  pendingRequestIds: SocialRequestId[];
}

/** A direct question/request survives the tick in which it was asked. */
export interface SocialRequest {
  id: SocialRequestId;
  conversationId: ConversationId;
  requester: CharacterId;
  recipient: CharacterId;
  subject: string;
  about?: CharacterId;
  createdTurn: number;
  deadlineTurn?: number;
  importance: number;
  status: SocialRequestStatus;
  responseEventId?: string;
  resolutionEventId?: string;
}

// --- threads: what the mock engine actually runs --------------------------

export interface ThreadBeat {
  turn: number;
  actor: CharacterId;
  moveId: MoveId;
  heatAfter: number;
}

/**
 * The live pairwise exchange `lib/mockEngine.ts` resolves against.
 *
 * Both branches shipped a type called `Conversation` and they are not the same
 * object: Track A's carries turn-taking and topic salience for the `sim/` port,
 * this one carries `heat` and `beats` for the engine being played today. One
 * name for two models is the two-sources-of-truth bug this repo has already
 * been bitten by, so the engine's is named for what it is.
 *
 * This is scaffolding with a deadline: when the `sim/` port lands, `Thread`
 * folds into `Conversation` and disappears.
 */
export interface Thread {
  id: ThreadId;
  participants: CharacterId[];
  location: LocationId;
  topicId?: TopicId;
  startedTurn: number;
  lastTurn: number;
  /** 0..100. Above 60 this exchange is an argument. */
  heat: number;
  beats: ThreadBeat[];
  status: "open" | "closed";
}

export interface PendingRequest {
  id: string;
  from: CharacterId;
  to: CharacterId;
  moveId: MoveId;
  topicId?: TopicId;
  turnAsked: number;
  expiresTurn: number;
}

export type ScenarioPhase =
  | "suspicion"
  | "investigation"
  | "reckoning"
  | "resolved";

/** Derived every tick from character locations — never written by hand. */
export interface SceneState {
  location: LocationId;
  presentCharacters: CharacterId[];
}

export interface WorldState {
  turn: number;

  /** Time is integers. `clock` is derived for display — see `lib/clock.ts`. */
  day: number;
  /** 0..23 — moves already spent today. 08:00 + slot * 30 minutes. */
  slot: number;

  characters: Record<CharacterId, Character>;

  locations: Record<LocationId, Location>;
  topics: Record<TopicId, Topic>;

  /** What the mock engine resolves against. */
  threads: Record<ThreadId, Thread>;
  pendingRequests: PendingRequest[];

  /**
   * Track A's model, populated by the `sim/` port. Optional until that port
   * lands and takes over from `threads`.
   */
  conversations?: Record<ConversationId, Conversation>;
  socialRequests?: Record<SocialRequestId, SocialRequest>;

  scene: SceneState;

  phase: ScenarioPhase;
  /** Set when the scenario resolves. Terminal. */
  ending?: string;

  rngSeed: number;
}

// --- moves and events -----------------------------------------------------

export interface Move {
  id: MoveId;
  actor: CharacterId;
  target?: CharacterId;
  args?: Record<string, unknown>;
}

export interface SimEvent {
  id: string;
  turn: number;
  type: string;

  actor?: CharacterId;
  target?: CharacterId;

  description: string;

  OnScene: CharacterId[];
}

export interface ResolvedMove {
  move: Move;
  witnessedByPlayer: boolean;
  threadId?: ThreadId;
}

export interface RelationshipDelta {
  sourceActor: CharacterId;
  from: CharacterId;
  to: CharacterId;
  field: RelationshipAxis;
  before: number;
  after: number;
  threadId?: ThreadId;
}

/** Track B realizes these deterministic facts as dialogue. */
export interface PendingUtterance {
  speaker: CharacterId;
  move: Move;
  mood: string;
  relationshipSnapshot: Relationship;
  speakerBeliefs: Belief[];
  retrievedMemories: Memory[];
  witnessedByPlayer: boolean;

  turn: number;
  speakerName: string;
  traits: string[];
  targetName?: string;
  /** The third party in a three-party move — talked about, not addressed. */
  subjectName?: string;
  castNames: string[];

  /** The topic LABEL only. Evidence claims never reach a prompt. */
  topicLabel?: string;
  threadBeats: string[];
  heat: number;
}

export interface Utterance {
  speaker: CharacterId;
  moveId: MoveId;
  line: string;
  deliveryNote?: string;
}

export interface RealizedLine {
  line: string;
  deliveryNote?: string;
}

/** The shared multi-actor result contract. */
export interface TickResult {
  state: WorldState;
  events: SimEvent[];
  log: ResolvedMove[];
  deltas: RelationshipDelta[];
  utterances: Utterance[];
  /** Events from the night pass, rendered as a "while you slept" digest. */
  overnight?: SimEvent[];
  /** Track B's future input. */
  pendingUtterances?: PendingUtterance[];
  eligibleActors?: CharacterId[];
}
