/**
 * The shared contract. Every track imports this file.
 *
 * Update 1 ("Conversations, Consequences, and Somewhere To Go") is the one
 * deliberate unfreezing of this file — see `plan.md` §3. It folds in what
 * `ai/types.ts` used to mirror as a shim (that file is now deleted) and adds
 * conversations, topics, locations, time and the fifth relationship axis.
 */

export type CharacterId = string;
export type MoveId = string;
export type TopicId = string;
export type LocationId = string;
export type ConversationId = string;

export type RelationshipAxis =
  | "trust"
  | "affection"
  | "respect"
  | "fear"
  | "anger";

/**
 * Directed and pairwise: `relationships[A][B]` is A's view of B. Never write
 * both directions in one effect unless the move explicitly says so.
 *
 * `baseline` is what the end-of-tick decay pass pulls toward — without it,
 * `fear` was a ratchet with no move in the game able to lower it.
 * `lastDelta` is what moved this tick; prompts and bar animations both read it.
 * `flags` are discrete states a move sets or clears.
 * `history` is the ledger behind "who was what before".
 */
export interface Relationship {
  trust: number;
  affection: number;
  respect: number;
  fear: number;
  anger: number;

  baseline: Record<RelationshipAxis, number>;
  lastDelta: Partial<Record<RelationshipAxis, number>>;
  flags: string[];
  history: RelationshipEvent[];
}

export type RelationshipStatus =
  | "close"
  | "friend"
  | "ally"
  | "neutral"
  | "wary"
  | "rival"
  | "estranged"
  | "hostile";

export interface RelationshipEvent {
  turn: number;
  was: RelationshipStatus;
  now: RelationshipStatus;
  /** Memory or move id that caused it. */
  because?: string;
}

export type MemoryTier = "direct" | "overheard" | "told";

export interface Memory {
  id: string;
  turn: number;

  actor: CharacterId;
  target?: CharacterId;

  /** Templated by the engine — never generated by a model. */
  description: string;
  tags: string[];
  importance: number;

  /** -1..1, how good or bad this was for the owner. */
  valence: number;
  tier: MemoryTier;
  /** false = planted by SpreadRumor. The owner cannot tell. */
  accurate: boolean;

  /** A MAJOR event: exempt from the cap, floored on decay. */
  core: boolean;

  topicId?: TopicId;
  conversationId?: ConversationId;
}

export interface Belief {
  id: string;
  /** Who this belief is about. A free-text description alone is untestable. */
  subject: CharacterId;
  axis?: RelationshipAxis;
  description: string;
  confidence: number;
  sourceMemoryId?: string;
}

export interface CharacterState {
  mood: string;
  emotions: Record<string, number>;
}

export interface Character {
  id: CharacterId;
  name: string;

  traits: string[];

  state: CharacterState;

  relationships: Record<CharacterId, Relationship>;

  memories: Memory[];
  beliefs: Belief[];

  goals: string[];

  location: LocationId;
  activeConversationId?: ConversationId;
}

// --- world furniture ------------------------------------------------------

export interface Location {
  id: LocationId;
  name: string;
  connectsTo: LocationId[];
  /** Conversations here are not overheard by anyone outside. */
  private: boolean;
}

export interface Evidence {
  id: string;
  topicId: TopicId;
  claim: string;
  heldBy: CharacterId[];
  /** false = planted. Nobody holding it can tell. */
  accurate: boolean;
  /** Who it implicates. */
  pointsAt?: CharacterId;
  /** 0..1 contribution to a suspect's confidence score. */
  weight: number;
  /** Locked evidence needs a condition met before it can be obtained. */
  locked?: boolean;
}

export interface Topic {
  id: TopicId;
  label: string;
  secret: boolean;
  awareOf: CharacterId[];
  evidence: Evidence[];
}

export interface ConversationBeat {
  turn: number;
  actor: CharacterId;
  moveId: MoveId;
  heatAfter: number;
}

export interface Conversation {
  id: ConversationId;
  participants: CharacterId[];
  location: LocationId;
  topicId?: TopicId;
  startedTurn: number;
  lastTurn: number;
  /** 0..100. Above 60 this conversation is an argument. */
  heat: number;
  beats: ConversationBeat[];
  status: "open" | "closed";
}

export interface PendingRequest {
  id: string;
  from: CharacterId;
  to: CharacterId;
  moveId: MoveId;
  topicId?: TopicId;
  turnAsked: number;
  expiresTurn: number;
}

export type ScenarioPhase =
  | "suspicion"
  | "investigation"
  | "reckoning"
  | "resolved";

/** Derived every tick from character locations — never written by hand. */
export interface SceneState {
  location: LocationId;
  presentCharacters: CharacterId[];
}

export interface WorldState {
  turn: number;

  /** Time is integers. `clock` is derived for display — see `lib/clock.ts`. */
  day: number;
  /** 0..23 — moves already spent today. 08:00 + slot * 30 minutes. */
  slot: number;

  characters: Record<CharacterId, Character>;

  locations: Record<LocationId, Location>;
  topics: Record<TopicId, Topic>;
  conversations: Record<ConversationId, Conversation>;
  pendingRequests: PendingRequest[];

  scene: SceneState;

  phase: ScenarioPhase;
  /** Set when the scenario resolves. Terminal. */
  ending?: string;

  rngSeed: number;
}

export interface Move {
  id: MoveId;
  actor: CharacterId;
  target?: CharacterId;
  args?: Record<string, unknown>;
}

export interface SimEvent {
  id: string;
  turn: number;
  type: string;

  actor?: CharacterId;
  target?: CharacterId;
  description: string;

  OnScene: CharacterId[];
}

// --- the AI seam ----------------------------------------------------------

/**
 * What a model is given to write one line. Everything here is the speaker's
 * own view — there is deliberately no `WorldState` on this type, so prompt
 * assembly has nothing to reach into for a third party's real numbers.
 */
export interface PendingUtterance {
  speaker: CharacterId;
  move: Move;
  mood: string;
  relationshipSnapshot: Relationship;
  speakerBeliefs: Belief[];
  retrievedMemories: Memory[];
  witnessedByPlayer: boolean;

  turn: number;
  speakerName: string;
  traits: string[];
  targetName?: string;
  /** The third party in "tell X about Y" — talked about, never addressed. */
  subjectName?: string;
  /** Every character name in the world, for the hallucination check. */
  castNames: string[];

  /** What this conversation is about, if anything. Label only — never evidence. */
  topicLabel?: string;
  /** The last few beats, so a reply doesn't open as if nothing preceded it. */
  conversationBeats: string[];
  /** 0..100. Drives how hot the line should read. */
  heat: number;
}

export interface RealizedLine {
  line: string;
  deliveryNote?: string;
}
